apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: dev
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: storefront-ui-permissive
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: storefront-ui
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: backoffice-ui-permissive
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backoffice-ui
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: swagger-ui-permissive
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: swagger-ui
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: nginx-api-gateway-permissive
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-api-gateway
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: media-permissive
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: media
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: storefront-bff-permissive
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: storefront-bff
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: backoffice-bff-permissive
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backoffice-bff
  mtls:
    mode: PERMISSIVE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: default
  namespace: dev
spec:
  host: "*.dev.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: location
  namespace: dev
spec:
  hosts:
  - location
  - location.dev.svc.cluster.local
  http:
  - route:
    - destination:
        host: location
        port:
          number: 80
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: "5xx,connect-failure,refused-stream"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tax
  namespace: dev
spec:
  hosts:
  - tax
  - tax.dev.svc.cluster.local
  http:
  - route:
    - destination:
        host: tax
        port:
          number: 80
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: "5xx,connect-failure,refused-stream"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-cart-callers
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cart
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/dev/sa/backoffice-bff
        - cluster.local/ns/dev/sa/storefront-bff
        - cluster.local/ns/dev/sa/order
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-customer-callers
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: customer
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/dev/sa/backoffice-bff
        - cluster.local/ns/dev/sa/storefront-bff
        - cluster.local/ns/dev/sa/order
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-inventory-callers
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/dev/sa/backoffice-bff
        - cluster.local/ns/dev/sa/storefront-bff
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-location-callers
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: location
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/dev/sa/backoffice-bff
        - cluster.local/ns/dev/sa/storefront-bff
        - cluster.local/ns/dev/sa/tax
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-media-callers
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: media
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/dev/sa/backoffice-bff
        - cluster.local/ns/dev/sa/storefront-bff
        - cluster.local/ns/dev/sa/product
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-order-callers
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: order
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/dev/sa/backoffice-bff
        - cluster.local/ns/dev/sa/storefront-bff
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-payment-callers
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: payment
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/dev/sa/backoffice-bff
        - cluster.local/ns/dev/sa/storefront-bff
        - cluster.local/ns/dev/sa/order
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-payment-paypal-callers
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-paypal
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/dev/sa/backoffice-bff
        - cluster.local/ns/dev/sa/storefront-bff
        - cluster.local/ns/dev/sa/payment
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-product-callers
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: product
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/dev/sa/backoffice-bff
        - cluster.local/ns/dev/sa/storefront-bff
        - cluster.local/ns/dev/sa/order
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-search-callers
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: search
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/dev/sa/backoffice-bff
        - cluster.local/ns/dev/sa/storefront-bff
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-tax-callers
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tax
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/dev/sa/backoffice-bff
        - cluster.local/ns/dev/sa/storefront-bff
        - cluster.local/ns/dev/sa/order
