apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - ingress.yaml
  - istio/namespace.yaml
  - istio/mtls.yaml
  - istio/destination-rules.yaml
  - istio/virtual-services.yaml
  - istio/authorization-policies.yaml
  - limitrange.yaml
  - observability/instrumentation.yaml
patches:
  - path: otel-inject-patch.yaml
    target:
      kind: Deployment
      name: "^(cart|customer|inventory|location|media|order|payment|payment-paypal|product|search|tax|sampledata|backoffice-bff|storefront-bff)$"
  - path: payment-liquibase-clear-checksums-patch.yaml
    target:
      kind: Deployment
      name: payment
  - path: backend-issuer-patch.yaml
    target:
      kind: Deployment
      name: "^(cart|customer|inventory|location|media|order|payment|payment-paypal|product|search|tax)$"
  - path: replicas-active.yaml
    target:
      kind: Deployment
  - path: sampledata-replicas-dormant.yaml
    target:
      kind: Deployment
      name: sampledata
  - path: istio/sidecar-resources-patch.yaml
    target:
      kind: Deployment
  - path: istio/keycloak-oauth-patch.yaml
  - path: db-url-patch.yaml
  - path: redis-patch.yaml
  - path: payment-paypal-public-url-patch.yaml
  - path: payment-application-public-url-patch.yaml
  - path: search-topic-patch.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: yas
      yas.nashtechglobal.com/environment: dev
    includeSelectors: true
images:
  - name: docker.io/emanhthangngot/yas-cart
    newTag: a50e8927e328
  - name: docker.io/emanhthangngot/yas-customer
    newTag: a4379fb34b04
  - name: docker.io/emanhthangngot/yas-inventory
    newTag: 91f23f2861e8
  - name: docker.io/emanhthangngot/yas-location
    newTag: a0e3654129e2
  - name: docker.io/emanhthangngot/yas-media
    newTag: ce0f1ae2d684
  - name: docker.io/emanhthangngot/yas-order
    newTag: 2e13db21a12a
  - name: docker.io/emanhthangngot/yas-payment
    newTag: 2e13db21a12a
  - name: docker.io/emanhthangngot/yas-payment-paypal
    newTag: a50e8927e328
  - name: docker.io/emanhthangngot/yas-product
    newTag: ce0f1ae2d684
  - name: docker.io/emanhthangngot/yas-search
    newTag: a50e8927e328
  - name: docker.io/emanhthangngot/yas-tax
    newTag: a0e3654129e2
  - name: docker.io/emanhthangngot/yas-sampledata
    newTag: a50e8927e328
  - name: docker.io/emanhthangngot/yas-backoffice-bff
    newTag: 256d69a55c8e
  - name: docker.io/emanhthangngot/yas-storefront-bff
    newTag: 0ff7e3c1ebcb
  - name: docker.io/emanhthangngot/yas-backoffice
    newTag: a50e8927e328
  - name: docker.io/emanhthangngot/yas-storefront
    newTag: a50e8927e328
