apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - ingress.yaml
  - istio/namespace.yaml
  - istio/mtls.yaml
  - istio/destination-rules.yaml
  - istio/virtual-services.yaml
  - istio/authorization-policies.yaml
  - limitrange.yaml
  - observability/instrumentation.yaml
patches:
  - path: otel-inject-patch.yaml
    target:
      kind: Deployment
      name: "^(cart|customer|inventory|location|media|order|payment|payment-paypal|product|search|tax|sampledata|backoffice-bff|storefront-bff)$"
  - path: payment-liquibase-clear-checksums-patch.yaml
    target:
      kind: Deployment
      name: payment
  - path: backend-issuer-patch.yaml
    target:
      kind: Deployment
      name: "^(cart|customer|inventory|location|media|order|payment|payment-paypal|product|search|tax)$"
  - path: replicas-active.yaml
    target:
      kind: Deployment
  - path: sampledata-replicas-dormant.yaml
    target:
      kind: Deployment
      name: sampledata
  - path: istio/sidecar-resources-patch.yaml
    target:
      kind: Deployment
  - path: istio/keycloak-oauth-patch.yaml
  - path: db-url-patch.yaml
  - path: redis-patch.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: yas
      yas.nashtechglobal.com/environment: dev
    includeSelectors: true
images:
  - name: docker.io/emanhthangngot/yas-cart
    newTag: ac337abc022f
  - name: docker.io/emanhthangngot/yas-customer
    newTag: ac337abc022f
  - name: docker.io/emanhthangngot/yas-inventory
    newTag: ac337abc022f
  - name: docker.io/emanhthangngot/yas-location
    newTag: ac337abc022f
  - name: docker.io/emanhthangngot/yas-media
    newTag: ac337abc022f
  - name: docker.io/emanhthangngot/yas-order
    newTag: ac337abc022f
  - name: docker.io/emanhthangngot/yas-payment
    newTag: ac337abc022f
  - name: docker.io/emanhthangngot/yas-payment-paypal
    newTag: ac337abc022f
  - name: docker.io/emanhthangngot/yas-product
    newTag: ac337abc022f
  - name: docker.io/emanhthangngot/yas-search
    newTag: ac337abc022f
  - name: docker.io/emanhthangngot/yas-tax
    newTag: ac337abc022f
  - name: docker.io/emanhthangngot/yas-sampledata
    newTag: main
  - name: docker.io/emanhthangngot/yas-backoffice-bff
    newTag: ac337abc022f
  - name: docker.io/emanhthangngot/yas-storefront-bff
    newTag: ac337abc022f
  - name: docker.io/emanhthangngot/yas-backoffice
    newTag: main
  - name: docker.io/emanhthangngot/yas-storefront
    newTag: main
