apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yas-storefront-media
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /media/$2
spec:
  ingressClassName: nginx
  rules:
    - host: yas.staging.local
      http:
        paths:
          - path: /api/media(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nginx
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yas-storefront
spec:
  ingressClassName: nginx
  rules:
    - host: yas.staging.local
      http:
        paths:
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: swagger-ui
                port:
                  number: 8080
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: storefront-bff
                port:
                  number: 80
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: storefront-bff
                port:
                  number: 80
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: storefront-bff
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: storefront-ui
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yas-keycloak
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: yas.staging.local:30846
spec:
  ingressClassName: nginx
  rules:
    - host: yas.staging.local
      http:
        paths:
          - path: /realms
            pathType: Prefix
            backend:
              service:
                name: identity
                port:
                  number: 80
          - path: /resources
            pathType: Prefix
            backend:
              service:
                name: identity
                port:
                  number: 80
