apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
  - ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: yas
      yas.nashtechglobal.com/environment: staging
    includeSelectors: true
images:
  - name: docker.io/emanhthangngot/yas-cart
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-customer
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-inventory
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-location
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-media
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-order
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-payment
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-payment-paypal
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-product
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-promotion
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-rating
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-search
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-tax
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-webhook
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-sampledata
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-recommendation
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-backoffice-bff
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-storefront-bff
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-backoffice
    newTag: v0.0.0
  - name: docker.io/emanhthangngot/yas-storefront
    newTag: v0.0.0
patches:
  - target:
      kind: Deployment
    path: replicas-dormant.yaml
