apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: developer
resources:
  - ../base
labels:
  - pairs:
      app.kubernetes.io/part-of: yas
      yas.nashtechglobal.com/environment: developer
    includeSelectors: true
images:
  - name: docker.io/emanhthangngot/yas-sampledata
    newTag: main
patches:
  - path: env-patch.yaml
    target:
      kind: Job
      name: sampledata-seed-once
