apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yas-storefront
spec:
  ingressClassName: traefik
  rules:
    - host: yas.developer.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: storefront-ui
                port:
                  number: 3000
