apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: developer
resources:
  - ../../base
  - ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: yas
      yas.nashtechglobal.com/environment: developer
    includeSelectors: true
images:
  - name: docker.io/emanhthangngot/yas-cart
    newTag: main
  - name: docker.io/emanhthangngot/yas-customer
    newTag: main
  - name: docker.io/emanhthangngot/yas-inventory
    newTag: main
  - name: docker.io/emanhthangngot/yas-location
    newTag: main
  - name: docker.io/emanhthangngot/yas-media
    newTag: main
  - name: docker.io/emanhthangngot/yas-order
    newTag: main
  - name: docker.io/emanhthangngot/yas-payment
    newTag: main
  - name: docker.io/emanhthangngot/yas-payment-paypal
    newTag: main
  - name: docker.io/emanhthangngot/yas-product
    newTag: main
  - name: docker.io/emanhthangngot/yas-search
    newTag: main
  - name: docker.io/emanhthangngot/yas-tax
    newTag: main
  - name: docker.io/emanhthangngot/yas-backoffice-bff
    newTag: main
  - name: docker.io/emanhthangngot/yas-storefront-bff
    newTag: main
  - name: docker.io/emanhthangngot/yas-backoffice
    newTag: main
  - name: docker.io/emanhthangngot/yas-storefront
    newTag: main
patches:
  - target:
      kind: Deployment
    path: replicas-dormant.yaml
  - target:
      kind: Deployment
      name: sampledata
    path: sampledata-replicas-dormant.yaml
