apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: developer
resources:
  - ../../base
  - ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: yas
      yas.nashtechglobal.com/environment: developer
    includeSelectors: true
images:
  - name: docker.io/emanhthangngot/yas-cart
    newTag: main
  - name: docker.io/emanhthangngot/yas-customer
    newTag: main
  - name: docker.io/emanhthangngot/yas-inventory
    newTag: main
  - name: docker.io/emanhthangngot/yas-location
    newTag: main
  - name: docker.io/emanhthangngot/yas-media
    newTag: main
  - name: docker.io/emanhthangngot/yas-order
    newTag: main
  - name: docker.io/emanhthangngot/yas-payment
    newTag: main
  - name: docker.io/emanhthangngot/yas-payment-paypal
    newTag: main
  - name: docker.io/emanhthangngot/yas-product
    newTag: main
  - name: docker.io/emanhthangngot/yas-search
    newTag: main
  - name: docker.io/emanhthangngot/yas-tax
    newTag: main
  - name: docker.io/emanhthangngot/yas-sampledata
    newTag: main
  - name: docker.io/emanhthangngot/yas-backoffice-bff
    newTag: main
  - name: docker.io/emanhthangngot/yas-storefront-bff
    newTag: 183159ae817c
  - name: docker.io/emanhthangngot/yas-backoffice
    newTag: main
  - name: docker.io/emanhthangngot/yas-storefront
    newTag: main
patches:
  - path: backend-issuer-patch.yaml
    target:
      kind: Deployment
      name: "^(cart|customer|inventory|location|media|order|payment|payment-paypal|product|search|tax)$"
  - path: istio/keycloak-oauth-patch.yaml
  - path: db-url-patch.yaml
  - path: redis-patch.yaml
  - path: payment-paypal-public-url-patch.yaml
  - path: payment-application-public-url-patch.yaml
  - path: search-topic-patch.yaml
  - target:
      kind: Deployment
    path: replicas-active.yaml
  - target:
      kind: Deployment
      name: sampledata
    path: sampledata-replicas-dormant.yaml
