apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-mesh-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:emanhthangngot/yas-cd.git'
    path: overlays/mesh-demo
    targetRevision: lab2/task/integrate-service-mesh
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mesh-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
