apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../charts

resources:
  - yas-configuration.yaml
  - compat-services.yaml

helmCharts:
  - name: backend
    releaseName: cart
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-cart
        tag: main
      nameOverride: cart
      fullnameOverride: cart
      databaseName: cart
  - name: backend
    releaseName: customer
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-customer
        tag: main
      nameOverride: customer
      fullnameOverride: customer
      databaseName: customer
      extraEnvFroms:
        - secretRef:
            name: yas-keycloak-credentials-secret
      extraVolumes:
        - name: customer-application
          configMap:
            name: customer-application-configmap
      extraVolumeMounts:
        - name: customer-application
          mountPath: /opt/yas/customer
      extraApplicationConfigPaths:
        - /opt/yas/customer/customer-application.yaml
  - name: backend
    releaseName: inventory
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-inventory
        tag: main
      nameOverride: inventory
      fullnameOverride: inventory
      databaseName: inventory
  - name: backend
    releaseName: location
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-location
        tag: main
      nameOverride: location
      fullnameOverride: location
      databaseName: location
  - name: backend
    releaseName: media
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-media
        tag: main
      nameOverride: media
      fullnameOverride: media
      databaseName: media
      extraVolumes:
        - name: media-application
          configMap:
            name: media-application-configmap
      extraVolumeMounts:
        - name: media-application
          mountPath: /opt/yas/media
      extraApplicationConfigPaths:
        - /opt/yas/media/media-application.yaml
  - name: backend
    releaseName: order
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-order
        tag: main
      nameOverride: order
      fullnameOverride: order
      databaseName: order
  - name: backend
    releaseName: payment
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-payment
        tag: main
      nameOverride: payment
      fullnameOverride: payment
      databaseName: payment
  - name: backend
    releaseName: payment-paypal
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-payment-paypal
        tag: main
      nameOverride: payment-paypal
      fullnameOverride: payment-paypal
      databaseName: payment-paypal
      extraVolumes:
        - name: payment-paypal-application-config
          configMap:
            name: payment-paypal-application-configmap
      extraVolumeMounts:
        - name: payment-paypal-application-config
          mountPath: /opt/yas/payment-paypal
      extraApplicationConfigPaths:
        - /opt/yas/payment-paypal/payment-paypal-application.yaml
      startupProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 180
        successThreshold: 1
        tcpSocket:
          port: metric
      livenessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 60
        successThreshold: 1
        tcpSocket:
          port: metric
      readinessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 60
        successThreshold: 1
        tcpSocket:
          port: metric
  - name: backend
    releaseName: product
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-product
        tag: main
      nameOverride: product
      fullnameOverride: product
      databaseName: product
  - name: backend
    releaseName: search
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-search
        tag: main
      nameOverride: search
      fullnameOverride: search
      databaseName: search
      extraEnvFroms:
        - secretRef:
            name: yas-elasticsearch-credentials-secret
      extraVolumes:
        - name: search-application
          configMap:
            name: search-application-configmap
      extraVolumeMounts:
        - name: search-application
          mountPath: /opt/yas/search
      extraApplicationConfigPaths:
        - /opt/yas/search/search-application.yaml
  - name: backend
    releaseName: tax
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-tax
        tag: main
      nameOverride: tax
      fullnameOverride: tax
      databaseName: tax
  - name: backend
    releaseName: sampledata
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-sampledata
        tag: main
      nameOverride: sampledata
      fullnameOverride: sampledata
      databaseName: sampledata
  - name: backend
    releaseName: backoffice-bff
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-backoffice-bff
        tag: main
      nameOverride: backoffice-bff
      fullnameOverride: backoffice-bff
      databaseName: backoffice-bff
      extraEnvs:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: UI_HOST
          value: http://backoffice-ui:3000
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI
          value: http://identity:30846/realms/Yas/protocol/openid-connect/auth
      extraEnvFroms:
        - secretRef:
            name: yas-keycloak-credentials-secret
        - secretRef:
            name: yas-redis-credentials-secret
      extraVolumes:
        - name: yas-gateway-routes-config
          configMap:
            name: yas-gateway-routes-config-configmap
        - name: backoffice-bff-extra-config
          configMap:
            name: backoffice-bff-extra-configmap
      extraVolumeMounts:
        - name: yas-gateway-routes-config
          mountPath: /opt/yas/gateway-routes-config
        - name: backoffice-bff-extra-config
          mountPath: /opt/yas/extra-config
      extraApplicationConfigPaths:
        - /opt/yas/gateway-routes-config/gateway-routes-config.yaml
        - /opt/yas/extra-config/backoffice-bff-extra-config.yaml
  - name: backend
    releaseName: storefront-bff
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-storefront-bff
        tag: main
      nameOverride: storefront-bff
      fullnameOverride: storefront-bff
      databaseName: storefront-bff
      extraEnvs:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: UI_HOST
          value: http://storefront-ui:3000
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI
          value: http://identity:30846/realms/Yas/protocol/openid-connect/auth
      extraEnvFroms:
        - secretRef:
            name: yas-keycloak-credentials-secret
        - secretRef:
            name: yas-redis-credentials-secret
      extraVolumes:
        - name: yas-gateway-routes-config
          configMap:
            name: yas-gateway-routes-config-configmap
        - name: storefront-bff-extra-config
          configMap:
            name: storefront-bff-extra-configmap
      extraVolumeMounts:
        - name: yas-gateway-routes-config
          mountPath: /opt/yas/gateway-routes-config
        - name: storefront-bff-extra-config
          mountPath: /opt/yas/extra-config
      extraApplicationConfigPaths:
        - /opt/yas/gateway-routes-config/gateway-routes-config.yaml
        - /opt/yas/extra-config/storefront-bff-extra-config.yaml
  - name: ui
    releaseName: backoffice-ui
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-backoffice
        tag: main
      nameOverride: backoffice-ui
      fullnameOverride: backoffice-ui
  - name: ui
    releaseName: storefront-ui
    valuesInline:
      image:
        repository: docker.io/emanhthangngot/yas-storefront
        tag: main
      nameOverride: storefront-ui
      fullnameOverride: storefront-ui
  - name: swagger-ui
    releaseName: swagger-ui
    valuesInline:
      ingress:
        enabled: false
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 25m
          memory: 64Mi
